---
title: "Special teams Planning A Return of Kickoff (SPARK)"
output: html_document
---

# Introduction

If you ever watched an NFL came, you almost surely have heard an commentator say something like "Man, they could really use a spark here". This usually in reference to the losing team, who is in need of an explosive play to gain some momentum and get back in the game. One of the "sparks" that can ignite a team is an incredible kickoff return to give the receiving team great field position, setting the drive up for a higher likelihood of resulting in a field goal or touchdown.

The SPARK model (Special teams Planning A Return of Kickoff) predicts when the receiving team will return a kickoff out of their own endzone *instead* of taking a touchback. 

But why is such a model beneficial? When the receiving team returns a kickoff from their own endzone, they are usually worse off than if they performed a touchback. In turn, a receiving team returning a kickoff from their own endzone *benefits* the kicking team. Returning a kickoff from the endzone, instead of taking a touchback, results in several disadvantages for the receiving team:
    * worse starting field position
    * lower EPA
    * higher chance of turnover occurring

Despite the disadvantages, about 20% of kickoffs that reach the endzone are returned out of the endzone by the receiving team. If the kicking team could better anticipate an endzone return occurring, they may be better off kicking off into the receiving team's endzone *instead* of kicking it short of the goal line.

This analysis uses the data provided, supplemented with play-by-play data from the `nflfastR` package, to develop a model capable of predicting if the receiving team will return a kickoff out of their own endzone with __% accuracy.

# Special teams Planning A Return of Kickoff (SPARK)

## Data Preparation & Feature Engineering

In thinking about what might cause a team to run a kickoff out of the endzone, I attempt to create some features to help capture the state of the game just prior to the kickoff. Data used to develop the model is a combination of the provided data sets, as well as play-by-play data from the `nflfastR` package. The play-by-play data is used to generate features that describe certain aspects of the game *just prior* to each kickoff. The only predictors not known prior to kickoff are kickoff-direction and kickoff-depth (i.e. how far into the endzone the ball is kicked), however, these are variables that can be somewhat controlled by the kicking team.

The full set of features used in the model are:

 * did the prior drive result in a score? 
 * and if so did that score result in a lead change? 
 * how many timeouts are remaining at the time of kickoff? 
 * how many endzone returns have already been performed by the receiving team?

## Model

Several model were developed, each tuned using bootstrap resampling (stratified on the outcome of return type) and hyperparameters selected based on log loss. The outcome is somewhat unbalanced, since only about 20% of kickoffs that reach the endzone are returned out of the endzone by the receiving team. Therefore in  addition to high accuracy a good model must also be able to distinguish between outcomes so ROC-AUC was used as the performance metric to select hyperparameter values.

The final model chosen was a Random Forest model based on its ROC-AUC value (good distinction between each outcomes). 
describe random forest, pros/cons...


## Results

-mention the only input NOT known at time of kickoff is kick length, but that can be controlled by kicker/kicking team

## Limitations

 - kickoffs ay be decided in advance  not a random variable but themselves the outcome of a decision
 - model may be missing variables, mis-specified

## Conclusions

The model developed here can predict if the receiving team will return a kickoff out of their own endzone with __% accuracy. Hopefully teams can use this to achieve some marginal benefit in their kickoff strategy. (Also I want to thank Kaggle for providing the data to let me dive into this question which I've wondered about for years!) 